-- begin PROJECTSALES_ORDER
alter table PROJECTSALES_ORDER add constraint FK_PROJECTSALES_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references PROJECTSALES_CUSTOMER(ID)^
create index IDX_PROJECTSALES_ORDER_ON_CUSTOMER on PROJECTSALES_ORDER (CUSTOMER_ID)^
-- end PROJECTSALES_ORDER
-- begin PROJECTSALES_ORDER_LINE
alter table PROJECTSALES_ORDER_LINE add constraint FK_PROJECTSALES_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references PROJECTSALES_ORDER(ID)^
alter table PROJECTSALES_ORDER_LINE add constraint FK_PROJECTSALES_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references PROJECTSALES_PRODUCT(ID)^
create index IDX_PROJECTSALES_ORDER_LINE_ON_ORDER on PROJECTSALES_ORDER_LINE (ORDER_ID)^
create index IDX_PROJECTSALES_ORDER_LINE_ON_PRODUCT on PROJECTSALES_ORDER_LINE (PRODUCT_ID)^
-- end PROJECTSALES_ORDER_LINE
